ontoportal-lirmm/ontologies_linked_data

lib/ontologies_linked_data/concerns/ontology_submissions/submission_metadata_extractor.rb, lib/ontologies_linked_data/models/ontology_submission.rb, test/data/ontology_files/agrooeMappings-05-05-2016.owl, test/models/test_ontology_submission.rb
- Refactor `OntologySubmission::MetadataExtractor` module
- Extract `extract_metadata` action from `process_rdf`
- Update extract metadata test to cover owl:imports bugs
=> Refactor: Isolate "extract metadata" process from "generate_rdf_file" in submission parsing 

lib/ontologies_linked_data/models/users/user.rb
As a result of this issue [Update Login & Register views design #130](https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/130) , it was concluded that new fields ( `github_id`, `ordcid_id`, ) need to be added to the user model.
Add the fields `github_id` and `ordcid_id` to the `user model`.
=> Feature: Add github_id and ordcid_id to user model

lib/ontologies_linked_data/models/users/user.rb
When we call `users endpoint ` we will see `subscribed ` attribute.
Issue: https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/64
=> Add subscribed attribute to the user model

lib/ontologies_linked_data/serializer.rb, lib/ontologies_linked_data/serializers/json.rb
When we call this endpoint : 
https://data.stageportal.lirmm.fr/ontologies/INRAETHES/classes/http%3A%2F%2Fopendata.inrae.fr%2FthesaurusINRAE%2Fc_2ecd2d30 
we will see in the `@context` the `@language` of the request, like in the following : 
```json
"@context": {
"@language": "en"
"@vocab": "http://data.bioontology.org/metadata/",
},
```
Issue: https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/65
=> Add request language to @context

Gemfile, Gemfile.lock, lib/ontologies_linked_data/concerns/mappings/mapping_creator.rb, lib/ontologies_linked_data/models/users/user.rb, test/models/notes/test_note.rb, test/models/skos/test_collections.rb, test/models/skos/test_schemes.rb, test/models/skos/test_skos_xl.rb, test/models/test_class_main_lang.rb, test/models/test_class_request_lang.rb, test/models/test_ontology.rb, test/models/test_provisional_class.rb, test/test_case.rb
https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/63
- Add tests for the requested language using INRAETHES as the use case 
- Add request_store gem, used to save the requested language as a global variable for the current request.
- Some code refactoring in the old tests (e.g exist?)
=> Feature: Support multilingual - Add read one language from request parameter tests

lib/ontologies_linked_data/serializers/json.rb
if hash was missing @context key the json serializer throwed a nil exception
and the parameter `display_context=false` to any of the endpoints
=> Fix: json serializer nil exception

Gemfile.lock, lib/ontologies_linked_data/models/ontology_submission.rb, lib/ontologies_linked_data/monkeypatches/object.rb
For the submission metrics attribute instead of showing the `id', fetch  the metrics object attributes (classes, individuals, and properties)
-  add some metrics attributes as embed values for Submissions (https://github.com/ontoportal-lirmm/ontologies_linked_data/commit/8e6d9d007a6e620e446b083a8911a291b331817d)
=> Feature: embed metrics for submission model

lib/ontologies_linked_data/serializer.rb, lib/ontologies_linked_data/serializers/json.rb
This pull request aims to remove the assignment of platform languages to the requested language and return the requested language in @language. This will allow us to filter search results based solely on the requested language.
Related to: https://github.com/ontoportal-lirmm/goo/pull/32
And follow up of https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/73
1. 
2.
https://data.testportal.lirmm.fr/ontologies/INRAETHES/latest_submission?display=naturalLanguage
@syphax-bouazzouni
=> Feature: return requested languages in @language - part 2 - multiple langugaes

lib/ontologies_linked_data/serializer.rb, lib/ontologies_linked_data/serializers/json.rb
=> Feature: add request language to context follow up

lib/ontologies_linked_data/security/access_control.rb
Fix a bug, when checking the access writes of a list of models; but one it depending models is nil (e.g ontologies with views)
=> Fix: call to read_restricted?  only if instance_to_base_on not nil

lib/ontologies_linked_data/models/ontology_submission.rb, lib/ontologies_linked_data/utils/file.rb, test/models/test_ontology_submission.rb
fix https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/42
follow up on this https://github.com/ncbo/ontologies_linked_data/pull/144
Now with this PR, a submission is archived we have two new behaviors 
1. Zip the archived submission uploaded file  and save in the attribute `uploadedFilePath` the new zipped file 
2. If the archived submission is zipped, remove the unzipped folder
=> Fix: Archived submission space optimization

Gemfile.lock, lib/ontologies_linked_data/models/class.rb, lib/ontologies_linked_data/monkeypatches/object.rb, test/models/test_class_portal_lang.rb, test/models/test_class_request_lang.rb
This PR adds the final modifications and tests for the Multilingual topic (https://github.com/agroportal/project-management/issues/307) done in the PRs below: 
- https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/91 
- https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/85
- https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/83 
- https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/80 
- https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/73 
- https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/71
- https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/67 
- Fix the class portal language test for the new multilingual support (https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/93/commits/e1b9af …
=> Feature: Add request all languages unit test

Gemfile.lock, lib/ontologies_linked_data/models/class.rb, lib/ontologies_linked_data/models/ontology_submission.rb, lib/ontologies_linked_data/monkeypatches/object.rb, test/data/ontology_files/BRO_v3.5.owl, test/models/test_class_request_lang.rb, test/models/test_ontology_submission.rb, test/models/test_provisional_class.rb, test/solr/configsets/term_search/conf/schema.xml
This PR  update and implement the multi-lingual search.  With it, we can now for these three properties of Classes/Concepts: prefLabel, synonym, and definition.
1. Search in all languages. 
2. Search specifically in one language (e.g. fr, en, ...).
3. Search specifically in values with no language.
This was made possible by doing two main things; 
1. **Update our SOLR Schema to have dynamic fields**: to save all the values in different languages. For example, a resource that has labels in French, English and not tagged, we will have in SOLR the fields `prefLabel_fr` for those in French,  `prefLabel_en` for those in English, `prefLabel_none` for those with no languages, and lastly `prefLabel` for all the values in all languages mixed see …
=> Feature: Support multilangual search

Gemfile.lock, config/schemes/ontology_submission.yml, lib/ontologies_linked_data/models/ontology.rb, lib/ontologies_linked_data/models/ontology_submission.rb, test/models/test_ontology_submission_validators.rb
- Due to the complexity of testing the new validators in parallel to testing the new UI, we will temporarily disable the   following validators (and more precisely the new onUpdate callbacks) : https://github.com/agroportal/project-management/issues/393
- Fixed the categories of the submission metadata, following strictly the [new 2023 metadata model template ](https://docs.google.com/document/d/1NHFNUjwOV7_aBrwNqDDgSshLTVewiZsKnFPLWuKc-xY/edit#heading=h.obnku5w78cvr)
=> Feature: Disable the new validators & fix submission metadata categories 

Gemfile.lock, lib/ontologies_linked_data/models/ontology.rb
origin https://github.com/ncbo/ontologies_linked_data/commit/98bb4f71a0714a31c13de99646145bb6af5d898c
=> Fix: an issue with the GA4 Analytics migration

Gemfile.lock, lib/ontologies_linked_data/concerns/ontology_submissions/skos/skos_submission_roots.rb, lib/ontologies_linked_data/models/ontology_format.rb, lib/ontologies_linked_data/models/skos/collection.rb, lib/ontologies_linked_data/models/skos/scheme.rb, test/models/test_ontology_submission.rb, test/models/test_skos_submission.rb
*  replaced usage of RDF::SKOS with RDF::Vocab::SKOS (https://github.com/ontoportal-lirmm/ontologies_linked_data/commit/151f918c6f7378bea9bddcd3ac22848dbce7856b)
=> Fix: latest RDF version replaced RDF::SKOS with RDF::Vocab::SKOS

lib/ontologies_linked_data/utils/notifications.rb, lib/ontologies_linked_data/utils/notifier.rb, test/util/test_notifications.rb
fix https://github.com/agroportal/project-management/issues/456, by sending the note creation notification to ontologies admin in addition of the subscribed users
=> Fix: send note creation notification to also the admins

bin/owlapi-wrapper.jar, lib/ontologies_linked_data/models/users/user.rb, lib/ontologies_linked_data/utils/notifications.rb, test/models/test_ontology.rb, test/models/test_ontology_submission.rb, test/util/test_notifications.rb
* https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/138
* [feature: use latest version of owlapi wrapper v1.4.3](https://github.com/ontoportal-lirmm/ontologies_linked_data/commit/c94c8fce0a1cd5d8e5367ea60e8f870cb3abff1a)
* https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/140
=> Merge to master: Release 2.5.2 - fix note broken link and no owl:Ontology resources parsing

lib/ontologies_linked_data/utils/notifications.rb
Change the notes URL that we send in the notes emails from this from: `/notes/note_hash` to `/ontologies/ontology_acronym?p=notes`
=> Feature: Make notes url open in the ontology notes interface instead of a separate page

lib/ontologies_linked_data/concerns/ontology_submissions/submission_validators.rb
fix https://github.com/agroportal/project-management/issues/526
=> Fix: change dataDump default value to not use the rdf version

config/schemes/ontology_submission.yml, lib/ontologies_linked_data/services/submission_process/operations/submission_extract_metadata.rb, lib/ontologies_linked_data/services/submission_process/submission_processor.rb, test/data/ontology_files/agrooeMappings-05-05-2016.owl, test/models/test_ontology_submission.rb
fix https://github.com/agroportal/project-management/issues/582, this enables again the extraction of Agents and re-enforces the extraction process to not fail if only some of the extracted attributes are not valid, accepting the valid and revoking the invalid.
* Update metadata extractor to validate each extracted metadata separately to not crash all the process if only some fields are incorrect (https://github.com/ontoportal-lirmm/ontologies_linked_data/commit/f0ddab855ea5e7c721853a280e3249d36eccf7f1)
* Update submission extraction test to catch erroneous extracted value (https://github.com/ontoportal-lirmm/ontologies_linked_data/commit/b99d26ff90611c9d8ebf801fe9b2067bb61caeb5)
* Update the metadata extractor to extract agents (https://github.com/ontoportal-lirmm/ontologies_linked_data/p …
=> Fix: Metadata extraction of erronous values and Agent extraction

config/config.rb.sample, lib/ontologies_linked_data/config/config.rb, lib/ontologies_linked_data/models/portal_config.rb, test/models/test_portal_configuration.rb
fix https://github.com/agroportal/project-management/issues/592, by adding a model to define the portal configuration, containing the following  attributes: 
```ruby
model :SemanticArtefactCatalogue, namespace: :mod, name_with: :acronym
attribute :acronym, enforce: [:unique, :existence]
attribute :title, namespace: :dcterms, enforce: [:existence]
attribute :color, enforce: [:existence, :valid_hash_code]
attribute :description, namespace: :dcterms
attribute :logo, namespace: :foaf, enforce: [:url]
attribute :numberOfArtefacts, namespace: :mod, handler: :ontologies_count
attribute :federated_portals
attribute :fundedBy, enforce: [:list] 
```
the model is not saved in the triple store, but use the configuration files, to fill its attributes.
```ruby 
config.ui_name                       = …
```
=> Feature: Add portal configuration model reading from config file

lib/ontologies_linked_data/models/ontology.rb
Related [issue #134](https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/134)
Add mappings to `Ontologies` contextual API links
=> Feature: Add mappings to `Ontologies` contextual API links

lib/ontologies_linked_data/models/base.rb
Prevent showing sensitive data using that serialize_never helper in the Goo models.
=> Fix : prevent serialization of attributes tagged as :serialize_never 

lib/ontologies_linked_data/models/category.rb
Make Category model accept multiple values for parent category instead of a single value.
**Email Christelle Pierkot**
> J'ai besoin par exemple que ma catégorie Atmosphere ait pour parents les categories Earth et Climate. D’après ce que j'ai vu, on ne peut assigner qu'un seul parent car c'est une liste déroulante qui est proposée.
=> Feature: Parent category multiple values

lib/ontologies_linked_data/models/ontology_submission.rb
This change ensures that only the file name (not the full path) is used, mitigating the risk of LFI attacks.
=> Fix : Prevent potential LFI by ensuring filename uses basename

lib/ontologies_linked_data/models/class.rb, lib/ontologies_linked_data/models/ontology_submission.rb, test/data/ontology_files/functraits.ttl, test/models/test_skos_submission.rb
fix https://github.com/lifewatch-eric/ecoportal_web_ui/issues/80, by filtring out class children if they are not in the current scheme and does not have children.
=> Feature: filter class children by a scheme

lib/ontologies_linked_data/concerns/concepts/concept_tree.rb, test/models/test_class.rb
Fix https://github.com/agroportal/project-management/issues/629. The issue is that when building the tree, we go from the root to the selected node. On each level, we fetch the current node children, and in this step, we have a maximum threshold of the count of children to fetch by node, which is 99. 
The issue is if in those 99 fetched children none of them lead to the selected node, the script stops without reaching the final level on which the selected node is. 
There is this documentation here, on how the tree endpoint works: https://doc.jonquetlab.lirmm.fr/share/f86bfc29-a0f1-4ccf-8d60-2be4e984106a
The fix was to make it possible to have a bigger threshold (for each try the threshold is multiplied by 10 for a maximum of 3 tries) if in the current level, none of the fetched nodes lead …
=> Fix: build tree threshold max issue

lib/ontologies_linked_data/models/category.rb
Issues discussed in: https://github.com/ontoportal-lirmm/ontologies_api/issues/94#issuecomment-2552993431
When we call `/categories?display=all` we don't see the ontologies related to the categories until we invoke it manually by using `display=ontologies`
Why: because in the Category model the attributes are not serialized by default including `:ontologies` 
Add `serialized_default` to all category attributes
=> Fix: serialize default category attributes to show ontologies

lib/ontologies_linked_data/mappings/mappings.rb, lib/ontologies_linked_data/models/ontology_submission.rb, lib/ontologies_linked_data/services/submission_process/operations/submission_diff_generator.rb
When a new ontology submission is processed,we have a step that fetch all the RestMappings and migrate them from the old submission to the new.
The issue is that the query fetch all the RestMappings (which are a lot in StagePortal), and then filter them to find only the ones related the current ontology processed,
The optimization was to filter directly the SPARQL query to filter by ACRONYM and paginate it if the number of RestMapping exceed 1000 mappings
In StagePortal, we went from 2 minutes, to 3s, for BFO (as it does not have any REST mappings)
* Paginate and regex filter to migrate_rest_mappings (https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/179/commits/3299cdba14e3d480f4b4ab5a35236ec4bd765026)
=> Feature: Optimize mappings migration in ontology process 

lib/ontologies_linked_data/concerns/mappings/mapping_counts.rb, test/models/test_mappings.rb
Follow up of https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/167, to fix https://github.com/ontoportal-lirmm/ontologies_api/issues/106, https://github.com/agroportal/project-management/issues/560
To be sure to clean and remove the mapping that no longer exists, handle the two following cases:
- An ontology no longer exists
- An ontology has a new version that no longer has mapping with the existent ontologies 
To be sure that we still have the same count as before, I did this sheet comparing the old and new ways of doing the counts https://docs.google.com/spreadsheets/d/1QWDQCIkEYPo8oSs2YA34t7OHx4xQDaHAWOQacpSpXj0/edit?usp=sharing 
* Refactor mapping count to simplify the code (https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/172/commits/650598b9fca65a06bf40f …
=> Feature: refactor mapping count module to simplify the code

Gemfile, Gemfile.lock, lib/ontologies_linked_data/config/config.rb, lib/ontologies_linked_data/services/submission_process/operations/submission_all_data_indexer.rb, test/models/skos/test_collections.rb, test/models/test_search.rb
* https://github.com/ontoportal-lirmm/goo/pull/67
* Add SPARQL query logging configuration (https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/181/commits/32c1aed4221e1b5f50a7931137092ee4ba62ca94)
* Remove cube monitoring (https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/181/commits/59de4a26aacb51a85725bd90b33442ad39b8876a)
* Update index all code to be faster in Virtuoso from  50s to 30s for INRAETHES  (https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/181/commits/52c31ff76d47fc3f294892ba9e06de7c7c65b3f6)
=> Feature: Add SPARQL query logging configuration

lib/ontologies_linked_data/config/config.rb, lib/ontologies_linked_data/models/mod/semantic_artefact.rb, lib/ontologies_linked_data/models/mod/semantic_artefact_distribution.rb, test/models/mod/test_artefact.rb, test/models/mod/test_artefact_distribution.rb
This pull request introduces the core models for the MOD-API, which are essential for managing semantic artefacts and their distributions.
1. **Semantic Artefact**  
- Represents a semantic artefact with relevant metadata and properties.  
2. **Semantic Artefact Distribution**  
- Represents a distribution of a semantic artefact, specifying its format and accessibility.  
3. Attributes that the models include are in this [GSheet](https://docs.google.com/spreadsheets/d/1nkb7s2WKZdba2g0gWCCOlY9stInbI4-GHfsEwQxdE9w/edit?gid=1259154776#gid=1259154776)
These models serve as the foundation for the MOD-API and will be used to facilitate data retrieval and management of semantic artefacts and their distributions.
=> Feature: Implement mod api models

lib/ontologies_linked_data/models/agents/agent.rb, lib/ontologies_linked_data/models/agents/identifier.rb
Added default serialization attributes for `Agents` model to show the creator only if the `display` parameter is put to all.
- `get /agents`
```
[
{
"name": "TEST",
"agentType": "person",
"acronym": null,
"email": null,
"homepage": null,
"identifiers": [
{
"notation": "0000-0002-3452-553X",
"schemaAgency": "ORCID"
}
],
"affiliations": [],
"@id": "http://0.0.0.0:9393/Agents/e8f7ea40-cae2-013d-4f89-0242ac130007",
"@type": "http://xmlns.com/foaf/0.1/Agent",
"@context": {
"@vocab": "http://data.bioontology.org/metadata/",
"agentType": "http://data.bioontology.org/metadata/agentType",
"name": "http://xmlns.com/foaf/0.1/name",
"homepage": "http://xmlns.com/foaf/0.1/homepage",
"acronym": "http://www.w3.org/2004/02/skos/core#altLabel",
"email": "http://xmlns.com/foaf/0.1/mbox",
"identifiers": …
```
=> Fix: Add default serialization attributes for agents

lib/ontologies_linked_data/models/mod/semantic_artefact.rb, test/models/mod/test_artefact.rb
- see https://github.com/ontoportal-lirmm/ontologies_api/issues/124
The solution is to activate the paging by default in this route
=> Fix: add paging by default when calling /artefacts

lib/ontologies_linked_data/concerns/semantic_artefact/attribute_fetcher.rb, lib/ontologies_linked_data/concerns/semantic_artefact/attribute_mapping.rb, lib/ontologies_linked_data/models/base.rb, lib/ontologies_linked_data/models/metric.rb, lib/ontologies_linked_data/models/mod/semantic_artefact.rb, lib/ontologies_linked_data/models/mod/semantic_artefact_distribution.rb, test/models/mod/test_artefact.rb, test/models/mod/test_artefact_distribution.rb
- Defining the metrics to the metric model
- Adding the metric attribute to the models as a link to the metric attribute 
- Adding the other metrics attribute to artefact and distribution
- metrics of artefacts
- metrics of distributions
=> Feature: add metrics in artefacts distributions

lib/ontologies_linked_data/models/base.rb, lib/ontologies_linked_data/models/mod/semantic_artefact.rb, lib/ontologies_linked_data/models/mod/semantic_artefact_catalog.rb, test/models/mod/test_artefact.rb, test/models/mod/test_artefact_catalog.rb
i added this to load all attributes including with `:handler`
https://github.com/ontoportal-lirmm/ontologies_linked_data/blob/e3a3f5745c078624748ec612fe47da74a15dd4c2/lib/ontologies_linked_data/models/base.rb#L47
but apparently it affect some test in the ontologies_api 
https://github.com/ontoportal-lirmm/ontologies_api/actions/runs/13455600001/job/37598830121?pr=117#step:6:1160
so we remove for now
=> Fix: remove all in goo attr to load

lib/ontologies_linked_data/concerns/semantic_artefact/attribute_fetcher.rb, lib/ontologies_linked_data/models/mod/semantic_artefact.rb
- See issue: https://github.com/agroportal/project-management/issues/688
When we call `/artefacts?pagesize=1` and we check the logs of 4store (triple store) we see a lot of sparql queries are executed (in the image is just a portion of it)
- Then number of queries that are executed for just one artefact  =  76 query (these are just for getting the attributes of the artefact)
- The reason for this is that 
1. the bring method in the attribute_fetcher.rb file, is bringing the attributes one by one
```ruby
attributes.each do |attr|
...
when :ontology
fetch_from_ontology(attr, mapped_attr)
end
...
...
def fetch_from_ontology(attr, mapped_attr)
@ontology.bring(*mapped_attr)
self.send("#{attr}=", @ontology.send(mapped_attr)) if @ontology.respond_to?(mapped_attr)
end
```
2. recalculating the …
=> Fix: optimization for artefacts model

lib/ontologies_linked_data/models/mod/semantic_artefact_catalog.rb, lib/ontologies_linked_data/models/users/user.rb
- Fix for: https://github.com/agroportal/project-management/issues/689
- Add the new routes links of mod-api
- Add all of the rest of links to the catalog 
- This is done to remove the logic in the home_controller: [here](https://github.com/ontoportal-lirmm/ontologies_api/blob/master/controllers/home_controller.rb#L14-L32) and since we are defining all the routes hardcoded in home_helper.rb: [here](https://github.com/ontoportal-lirmm/ontologies_api/blob/master/helpers/home_helper.rb#L20-L46)
=> Feature: add links to catalog

lib/ontologies_linked_data/models/users/oauth_authentication.rb
- If `email` is `nil`, the query `LinkedData::Models::User.where(email: email).first` would return the first user in the database, leading to unintended login as that user. 
- To prevent this, explicitly return `nil` if `email` is `nil`.
- Even if we fix this the logic behind Github Oauth is still broken, because i can change my github email (it doesn't require verification) and put one of a portal admin.
=> Fix : GitHub OAuth Misconfiguration Allows Logging In as Another User

lib/ontologies_linked_data/models/ontology_submission.rb
fix for:
- https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/219
- https://github.com/agroportal/project-management/issues/694
=> Fix: disable copying hasDomain from ontology to submission
