ontoportal-lirmm/ontologies_linked_data

- lib/ontologies_linked_data/serializers/json.rb
Fix https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/84#issuecomment-1562642721
> Fix: get serialized object submission only if include 'submission' attribute

- lib/ontologies_linked_data/models/category.rb
Discussed in meeting of June 2
> Feature: Update category model  to add default attribute to serialize  

- lib/ontologies_linked_data/concerns/concepts/concept_in_scheme.rb
- lib/ontologies_linked_data/concerns/concepts/concept_tree.rb
- lib/ontologies_linked_data/models/ontology_submission.rb
fix for https://github.com/ontoportal-lirmm/ontologies_api/issues/49
> Fix: make for a concept  isInActiveScheme an empty array if inScheme is empty

- Gemfile.lock
- lib/ontologies_linked_data/models/agents/agent.rb
- test/models/test_agent.rb
* add usage method to the agent models (https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/109/commits/5eb0ba9f6add430646ba36c05116182fcb2c9b2c)
* add units tests
> Feature: add usage method to the agent models

- config/schemes/ontology_submission.yml
Follow up of #108 
After a few other changes
> Fix ontology submission rework2

- Gemfile.lock
- lib/ontologies_linked_data/models/agents/agent.rb
- test/models/test_agent.rb
* Optimize the agents usages query, to do batch loading when fetching all agents (https://github.com/ontoportal-lirmm/ontologies_linked_data/commit/43f0fa9fe387bad0a04cd9a09da0b9fb593c9cfe)
> Fix: optimize fetch all agents usages query 

- lib/ontologies_linked_data/utils/notifier.rb
- test/util/test_notifications.rb
See https://github.com/ontoportal/ontologies_linked_data/pull/9
> Fix: login auth type mail options

- lib/ontologies_linked_data/concerns/analytics.rb
- lib/ontologies_linked_data/models/ontology.rb
- lib/ontologies_linked_data/models/users/user.rb
- test/models/test_analytics.rb
* https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/118
> Merge to master: release 2.4.1

- lib/ontologies_linked_data/utils/notifications.rb
Related issue: https://github.com/agroportal/project-management/issues/551
> Fix: notes email broken URL

- Gemfile
- Gemfile.lock
- lib/ontologies_linked_data/models/class.rb
- test/models/test_class_request_lang.rb
See details in https://github.com/ontoportal-lirmm/goo/pull/61
> Fix: show multiple languages tags

- lib/ontologies_linked_data/models/ontology_submission.rb
fix https://github.com/agroportal/project-management/issues/541
> Fix: remove default value of submission obsoleteParent

- lib/ontologies_linked_data/models/ontology.rb
fix https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/123
> Feature: add agent links to ontology model

- lib/ontologies_linked_data/models/ontology.rb
- lib/ontologies_linked_data/models/properties/annotation_property.rb
- lib/ontologies_linked_data/models/properties/datatype_property.rb
- lib/ontologies_linked_data/models/properties/object_property.rb
- lib/ontologies_linked_data/models/properties/ontology_property.rb
- test/models/test_ontology.rb
fix https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/142
> Feature: Add range and domain attributes for properties models

- lib/ontologies_linked_data/serializers/json.rb
Reverts ontoportal-lirmm/ontologies_linked_data#149 because of https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/149#issuecomment-2263740030
> Revert "Fix: uppercase Ids in the JSON api serializer "

- config/schemes/ontology_submission.yml
fix https://github.com/ontoportal-lirmm/bioportal_web_ui/issues/653
> Feature: add Brazilian to the enforced values of submission language attribute

- lib/ontologies_linked_data/models/resource.rb
- test/models/test_resource.rb
* filtering uris and literals in namespace_predict function
* add more tests to test_resource.rb
> Fix: Export jsonld content error if literals has a / or # (#173)

- lib/ontologies_linked_data/models/ontology.rb
- lib/ontologies_linked_data/models/ontology_submission.rb
* [add option to skip archiving in ontology deletion](https://github.com/ontoportal-lirmm/ontologies_linked_data/commit/8b519f1ec4fa44eb10c4de172881513b91a76a44)
> Feature: Add option to skip archiving in ontology delete

- lib/ontologies_linked_data/models/mod/semantic_artefact_catalog.rb
- Fix the metrics calculation 
- Refactor code by regrouping handler that have the same behavior
> Fix: refactor catalog model code

- lib/ontologies_linked_data/models/mod/semantic_artefact_catalog.rb
- Fix for: https://github.com/agroportal/project-management/issues/696
- Screenshot
> Fix mod-api root type

- lib/ontologies_linked_data/models/agents/agent.rb
NB: We have 2 `hasDomain` attributes:
- The first one is stored in LinkedData::Models::Ontology and is used for categories
- The second on is stored in LinkedData::Models::OntologySubmission and is used for subjects
> Feature: add subjects loading during agent serialization
